name: smart-factory-safety
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - opencv
  - pip
  - pip:
    - albumentations
    - ultralytics
